<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Usuario',
                'edit' => 1,
                'field' => 'name',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 3,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Contraseña',
                'edit' => 1,
                'field' => 'password',
                'id' => 4,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 5,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 6,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 7,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 8,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'user_belongsto_role_relationship',
                'id' => 9,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'display_name' => 'Roles',
                'edit' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'id' => 10,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'relationship',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Settings',
                'edit' => 0,
                'field' => 'settings',
                'id' => 11,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'hidden',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 12,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 13,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 14,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 15,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 16,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 17,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            17 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 18,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            18 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 19,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 20,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 21,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email Verified At',
                'edit' => 0,
                'field' => 'email_verified_at',
                'id' => 22,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            22 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 32,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:25","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max."}}}',
                'display_name' => 'Nombre del módulo',
                'edit' => 1,
                'field' => 'name',
                'id' => 33,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            24 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:25","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max."}}}',
                'display_name' => 'Nombre a mostrar',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 34,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            25 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required","messages":{"required":"El campo :attribute es requerido."}}}',
                'display_name' => 'Status',
                'edit' => 1,
                'field' => 'status',
                'id' => 35,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'checkbox',
            ),
            26 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 36,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            27 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 37,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            28 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 38,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            29 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'N°',
                'edit' => 0,
                'field' => 'id',
                'id' => 62,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            30 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:80","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'name',
                'id' => 63,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            31 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:250","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Descripción',
                'edit' => 1,
                'field' => 'description',
                'id' => 64,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            32 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:1|numeric","messages":{"required":"El campo :attribute es requerido.","min":"El campo :attribute admite como m\\u00ednimo :min"}}}',
                'display_name' => 'Precio',
                'edit' => 1,
                'field' => 'price',
                'id' => 65,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            33 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 72,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            34 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 73,
                'order' => 14,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            35 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 74,
                'order' => 15,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            36 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Api Token',
                'edit' => 0,
                'field' => 'api_token',
                'id' => 93,
                'order' => 10,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            37 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 94,
                'order' => 13,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            38 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'N°',
                'edit' => 0,
                'field' => 'id',
                'id' => 95,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:30","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
            'display_name' => 'Nombre (s)',
                'edit' => 1,
                'field' => 'first_name',
                'id' => 96,
                'order' => 2,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:30","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Apellidos',
                'edit' => 1,
                'field' => 'last_name',
                'id' => 97,
                'order' => 3,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            41 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre completo',
                'edit' => 1,
                'field' => 'full_name',
                'id' => 98,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'hidden',
            ),
            42 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"default":"hombre","options":{"hombre":"Hombre","mujer":"Mujer"}}',
                'display_name' => 'Género',
                'edit' => 1,
                'field' => 'gender',
                'id' => 99,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            43 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:150","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Domicilio fiscal',
                'edit' => 1,
                'field' => 'address',
                'id' => 100,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            44 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:0|numeric","messages":{"required":"El campo :attribute es requerido.","min":"El campo :attribute no admite numeros negativos."}}}',
                'display_name' => 'Num. Teléfono',
                'edit' => 1,
                'field' => 'phone',
                'id' => 101,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            45 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:16","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Rfc',
                'edit' => 1,
                'field' => 'rfc',
                'id' => 102,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            46 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
            'display_name' => 'Nombre o Rázon social (sin régimen capital)',
                'edit' => 1,
                'field' => 'reason',
                'id' => 103,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            47 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Correo electrónico',
                'edit' => 1,
                'field' => 'email',
                'id' => 104,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:1|numeric","messages":{"required":"El campo :attribute es requerido.","min":"El campo :attribute no admite numeros negativos."}}}',
                'display_name' => 'Código postal',
                'edit' => 1,
                'field' => 'postal_code',
                'id' => 105,
                'order' => 11,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            49 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 107,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            50 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 108,
                'order' => 14,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            51 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 109,
                'order' => 15,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            52 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Régimen fiscal',
                'edit' => 1,
                'field' => 'regime',
                'id' => 120,
                'order' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            53 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Uso de CFDI',
                'edit' => 1,
                'field' => 'cfdi_use',
                'id' => 121,
                'order' => 11,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            54 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
            'display_name' => 'Código del producto o servicio (SAT)',
                'edit' => 1,
                'field' => 'product_code',
                'id' => 122,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            55 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
            'display_name' => 'Unidad del producto o servicio (SAT)',
                'edit' => 1,
                'field' => 'unit_code',
                'id' => 123,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            56 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 124,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            57 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Customer Id',
                'edit' => 1,
                'field' => 'customer_id',
                'id' => 125,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            58 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Enlace PDF',
                'edit' => 1,
                'field' => 'link_pdf',
                'id' => 126,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            59 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Enlace XML',
                'edit' => 1,
                'field' => 'link_xml',
                'id' => 127,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            60 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Products',
                'edit' => 1,
                'field' => 'products',
                'id' => 128,
                'order' => 5,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            61 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 129,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            62 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 130,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            63 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Customer","table":"customers","type":"belongsTo","column":"customer_id","key":"id","label":"full_name","pivot_table":"customers","pivot":"0","taggable":"0"}',
                'display_name' => 'Cliente',
                'edit' => 1,
                'field' => 'invoice_belongsto_customer_relationship',
                'id' => 132,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            64 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Invoice Id',
                'edit' => 0,
                'field' => 'invoice_id',
                'id' => 135,
                'order' => 3,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            65 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 140,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            66 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Usuario',
                'edit' => 1,
                'field' => 'user',
                'id' => 141,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            67 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Contraseña',
                'edit' => 1,
                'field' => 'password',
                'id' => 142,
                'order' => 3,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            68 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'RFC',
                'edit' => 1,
                'field' => 'rfc',
                'id' => 143,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            69 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
            'display_name' => 'Nombre o Razón social (sin régimen capital)',
                'edit' => 1,
                'field' => 'name',
                'id' => 144,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            70 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Régimen fiscal',
                'edit' => 1,
                'field' => 'fiscal_regime',
                'id' => 145,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            71 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Certificado',
                'edit' => 1,
                'field' => 'certificate',
                'id' => 146,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'file',
            ),
            72 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Llave privada',
                'edit' => 1,
                'field' => 'private_key',
                'id' => 147,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'file',
            ),
            73 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Contraseña de llave privada',
                'edit' => 1,
                'field' => 'private_key_password',
                'id' => 148,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            74 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 150,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            75 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 151,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
        ));
        
        
    }
}