<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 3,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 4,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 5,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 6,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 7,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 8,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'user_belongsto_role_relationship',
                'id' => 9,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'display_name' => 'Roles',
                'edit' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'id' => 10,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Settings',
                'edit' => 0,
                'field' => 'settings',
                'id' => 11,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'hidden',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 12,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 13,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 14,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 15,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 16,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 17,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            17 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 18,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            18 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 19,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 20,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 21,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email Verified At',
                'edit' => 1,
                'field' => 'email_verified_at',
                'id' => 22,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            22 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 23,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:25","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max."}}}',
                'display_name' => 'Banco',
                'edit' => 1,
                'field' => 'bank',
                'id' => 24,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            24 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:14|min:13","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max.","min":"El campo :attribute acepta m\\u00ednimo :min."}}}',
                'display_name' => 'Número de tarjeta',
                'edit' => 1,
                'field' => 'number_card',
                'id' => 25,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            25 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max."}}}',
                'display_name' => 'Nombre del propietario',
                'edit' => 1,
                'field' => 'name',
                'id' => 26,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            26 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 27,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            27 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 28,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            28 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 29,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            29 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:16|min:15","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max.","min":"El campo :attribute acepta m\\u00ednimo :min."}}}',
                'display_name' => 'Número de cuenta',
                'edit' => 1,
                'field' => 'number_account',
                'id' => 30,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            30 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:18|min:17","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max.","min":"El campo :attribute acepta m\\u00ednimo :min."}}}',
                'display_name' => 'CLABE',
                'edit' => 1,
                'field' => 'clabe',
                'id' => 31,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            31 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 32,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            32 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:25","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max."}}}',
                'display_name' => 'Nombre del módulo',
                'edit' => 1,
                'field' => 'name',
                'id' => 33,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            33 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:25","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max."}}}',
                'display_name' => 'Nombre a mostrar',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 34,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            34 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required","messages":{"required":"El campo :attribute es requerido."}}}',
                'display_name' => 'Status',
                'edit' => 1,
                'field' => 'status',
                'id' => 35,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'checkbox',
            ),
            35 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 36,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            36 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 37,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            37 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 38,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            38 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 39,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:30","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute acepta maximo :max."}}}',
                'display_name' => 'Nombre del método de pago',
                'edit' => 1,
                'field' => 'name',
                'id' => 40,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 41,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            41 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 42,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            42 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 43,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            43 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 44,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            44 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'name',
                'id' => 45,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            45 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:100","messages":{"max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Descripción',
                'edit' => 1,
                'field' => 'description',
                'id' => 46,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            46 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 47,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            47 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 48,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            48 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 49,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            49 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 50,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            50 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'name',
                'id' => 51,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            51 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:50","messages":{"max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Dirección',
                'edit' => 1,
                'field' => 'address',
                'id' => 52,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            52 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 53,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            53 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 54,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            54 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 55,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            55 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 56,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            56 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'name',
                'id' => 57,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            57 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:10","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Simbolo',
                'edit' => 1,
                'field' => 'symbol',
                'id' => 58,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            58 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 59,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            59 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 60,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            60 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 61,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            61 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'N°',
                'edit' => 0,
                'field' => 'id',
                'id' => 62,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            62 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:80","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'name',
                'id' => 63,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            63 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:250","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Descripción',
                'edit' => 1,
                'field' => 'description',
                'id' => 64,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            64 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:1|numeric","messages":{"required":"El campo :attribute es requerido.","min":"El campo :attribute admite como m\\u00ednimo :min"}}}',
                'display_name' => 'Precio',
                'edit' => 1,
                'field' => 'price',
                'id' => 65,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            65 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:1|numeric","messages":{"required":"El campo :attribute es requerido.","min":"El campo :attribute admite como m\\u00ednimo :min"}}}',
                'display_name' => 'Cantidad mínima',
                'edit' => 1,
                'field' => 'stock_min',
                'id' => 66,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            66 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Código del producto',
                'edit' => 1,
                'field' => 'productCode',
                'id' => 67,
                'order' => 6,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            67 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Código de unidad',
                'edit' => 1,
                'field' => 'unitCode',
                'id' => 68,
                'order' => 7,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            68 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Category Id',
                'edit' => 1,
                'field' => 'category_id',
                'id' => 69,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            69 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Unit Id',
                'edit' => 1,
                'field' => 'unit_id',
                'id' => 70,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            70 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"validation":{"rule":"mimes:png,jpg|max:5000","messages":{"mimes":"Se permiten archivos PNG, JPG","max":"Se permiten archivos de tama\\u00f1o de hasta 5 MB"}}}',
                'display_name' => 'Imagen',
                'edit' => 1,
                'field' => 'image',
                'id' => 71,
                'order' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'image',
            ),
            71 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 72,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            72 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 73,
                'order' => 14,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            73 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 74,
                'order' => 15,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            74 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Category","table":"categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'Categoría',
                'edit' => 1,
                'field' => 'product_belongsto_category_relationship',
                'id' => 75,
                'order' => 11,
                'read' => 1,
                'required' => 1,
                'type' => 'relationship',
            ),
            75 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Unit","table":"units","type":"belongsTo","column":"unit_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'Unidad de medida',
                'edit' => 1,
                'field' => 'product_belongsto_unit_relationship',
                'id' => 76,
                'order' => 12,
                'read' => 1,
                'required' => 1,
                'type' => 'relationship',
            ),
            76 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 77,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            77 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Movimiento',
                'edit' => 1,
                'field' => 'name',
                'id' => 78,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            78 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Descripción',
                'edit' => 1,
                'field' => 'description',
                'id' => 79,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            79 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{"default":"E","options":{"E":"Entrada","S":"Salida","T":"Traspaso"}}',
                'display_name' => 'Tipo',
                'edit' => 1,
                'field' => 'type',
                'id' => 80,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            80 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 81,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            81 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 82,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            82 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 83,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            83 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 84,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            84 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Product Id',
                'edit' => 0,
                'field' => 'product_id',
                'id' => 85,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            85 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Office Id',
                'edit' => 0,
                'field' => 'office_id',
                'id' => 86,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            86 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Cantidad disponible',
                'edit' => 0,
                'field' => 'stock',
                'id' => 87,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            87 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 88,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            88 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 89,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            89 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 90,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            90 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"products","type":"belongsTo","column":"product_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'Producto',
                'edit' => 0,
                'field' => 'inventory_belongsto_product_relationship',
                'id' => 91,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            91 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Office","table":"offices","type":"belongsTo","column":"office_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'Sucursal',
                'edit' => 0,
                'field' => 'inventory_belongsto_office_relationship',
                'id' => 92,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            92 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Api Token',
                'edit' => 1,
                'field' => 'api_token',
                'id' => 93,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            93 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 94,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            94 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'N°',
                'edit' => 0,
                'field' => 'id',
                'id' => 95,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            95 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
            'display_name' => 'Nombre (s)',
                'edit' => 1,
                'field' => 'first_name',
                'id' => 96,
                'order' => 2,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            96 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Apellidos',
                'edit' => 1,
                'field' => 'last_name',
                'id' => 97,
                'order' => 3,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            97 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre completo',
                'edit' => 1,
                'field' => 'full_name',
                'id' => 98,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'hidden',
            ),
            98 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Sexo',
                'edit' => 1,
                'field' => 'gender',
                'id' => 99,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            99 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Dirección',
                'edit' => 1,
                'field' => 'address',
                'id' => 100,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            100 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Num. Teléfono',
                'edit' => 1,
                'field' => 'phone',
                'id' => 101,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            101 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Rfc',
                'edit' => 1,
                'field' => 'rfc',
                'id' => 102,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            102 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Razón social',
                'edit' => 1,
                'field' => 'reason',
                'id' => 103,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            103 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Correo electrónico',
                'edit' => 1,
                'field' => 'email',
                'id' => 104,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            104 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Código postal',
                'edit' => 1,
                'field' => 'postal_code',
                'id' => 105,
                'order' => 11,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            105 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'User Id',
                'edit' => 1,
                'field' => 'user_id',
                'id' => 106,
                'order' => 12,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            106 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Registrado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 107,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            107 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 13,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 108,
                'order' => 14,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            108 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Eliminado',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 109,
                'order' => 15,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            109 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 13,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"email","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'Usuario',
                'edit' => 1,
                'field' => 'customer_belongsto_user_relationship',
                'id' => 110,
                'order' => 16,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            110 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 111,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            111 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Nombre del template',
                'edit' => 1,
                'field' => 'template_name',
                'id' => 112,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            112 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 1,
                'details' => '{"default":"Marketing","options":{"Marketing":"Marketing","Autenticaci\\u00f3n":"Autenticaci\\u00f3n","Utilidad":"Utilidad"}}',
                'display_name' => 'Tipo del template',
                'edit' => 1,
                'field' => 'template_type',
                'id' => 113,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'select_dropdown',
            ),
            113 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Cuerpo del mensaje',
                'edit' => 1,
                'field' => 'message_body',
                'id' => 114,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            114 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"El campo :attribute admite maximo :max caracteres."}}}',
                'display_name' => 'Ejemplo del mensaje',
                'edit' => 1,
                'field' => 'example_message',
                'id' => 115,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            115 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 1,
                'details' => '{"default":"Pendiente","options":{"Pendiente":"Pendiente","Aprovado":"Aprovado","Cancelado":"Cancelado"}}',
                'display_name' => 'Status',
                'edit' => 1,
                'field' => 'status',
                'id' => 116,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'hidden',
            ),
            116 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 117,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            117 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 118,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            118 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 119,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
        ));
        
        
    }
}